import type { Book } from '@/types/book';

export let books: Book[] = [
  {
    id: '1',
    title: 'JavaScript Mastery',
    description: 'Learn JS deeply with modern examples and best practices.',
    price: 40,
    author: 'Admin User',
    category: 'Technology',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c',
    authorId: "1",
  },
  {
    id: '2',
    title: 'The Science World',
    description: 'A fascinating introduction to modern science.',
    price: 30,
    author: 'John Doe',
    category: 'Science',
    thumbnail: 'https://images.unsplash.com/photo-1509228468518-180dd4864904',
    authorId: "2",
  },
  {
    id: '3',
    title: 'History of Empires',
    description: 'Discover the rise and fall of great empires.',
    price: 22,
    author: 'Admin User',
    category: 'History',
    thumbnail: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e',
    authorId: "1",
  },
  {
    id: '4',
    title: 'Fantasy Tales',
    description: 'Dive into magical stories and epic worlds.',
    price: 18,
    author: 'Aria Smith',
    category: 'Fantasy',
    thumbnail: 'https://images.unsplash.com/photo-1519682337058-a94d519337bc',
    authorId: "4",
  },
  {
    id: '5',
    title: 'Biography: A Life',
    description: 'The inspiring journey of a remarkable person.',
    price: 28,
    author: 'Admin User',
    category: 'Biography',
    thumbnail: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
    authorId: "1",
  },
  {
    id: '6',
    title: 'Python Programming',
    description: 'Master Python from basics to advanced concepts.',
    price: 45,
    author: 'Sarah Johnson',
    category: 'Technology',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5',
    authorId: "6",
  },
  {
    id: '7',
    title: 'Quantum Physics',
    description: 'Understanding the quantum world made simple.',
    price: 35,
    author: 'Dr. Michael Chen',
    category: 'Science',
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb',
    authorId: "7",
  },
  {
    id: '8',
    title: 'Ancient Egypt',
    description: 'Explore the mysteries of ancient Egyptian civilization.',
    price: 26,
    author: 'John Doe',
    category: 'History',
    thumbnail: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368',
    authorId: "2",
  },
  {
    id: '9',
    title: 'Dragon Riders',
    description: 'An epic adventure in a world of dragons and magic.',
    price: 20,
    author: 'Aria Smith',
    category: 'Fantasy',
    thumbnail: 'https://images.unsplash.com/photo-1532012197267-da84d127e765',
    authorId: "4",
  },
  {
    id: '10',
    title: 'Steve Jobs Biography',
    description: 'The story of Apple\'s visionary founder.',
    price: 32,
    author: 'Walter Isaacson',
    category: 'Biography',
    thumbnail: 'https://images.unsplash.com/photo-1589998059171-988d887df646',
    authorId: "8",
  },
  {
    id: '11',
    title: 'Web Development Guide',
    description: 'Complete guide to modern web development.',
    price: 38,
    author: 'Sarah Johnson',
    category: 'Technology',
    thumbnail: 'https://images.unsplash.com/photo-1593720213428-28a5b9e94613',
    authorId: "6",
  },
  {
    id: '12',
    title: 'Space Exploration',
    description: 'Journey through the cosmos and beyond.',
    price: 29,
    author: 'Dr. Michael Chen',
    category: 'Science',
    thumbnail: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa',
    authorId: "7",
  },
  {
    id: '13',
    title: 'World War Chronicles',
    description: 'Detailed account of major world conflicts.',
    price: 24,
    author: 'Admin User',
    category: 'History',
    thumbnail: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1',
    authorId: "1",
  },
  {
    id: '14',
    title: 'The Wizard\'s Quest',
    description: 'A magical journey of courage and friendship.',
    price: 19,
    author: 'Aria Smith',
    category: 'Fantasy',
    thumbnail: 'https://images.unsplash.com/photo-1526243741027-444d633d7365',
    authorId: "4",
  },
  {
    id: '15',
    title: 'Einstein: A Life',
    description: 'The fascinating life of Albert Einstein.',
    price: 30,
    author: 'Walter Isaacson',
    category: 'Biography',
    thumbnail: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8',
    authorId: "8",
  },
  {
    id: '16',
    title: 'React & Next.js',
    description: 'Build modern web applications with React.',
    price: 42,
    author: 'Admin User',
    category: 'Technology',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee',
    authorId: "1",
  },
  {
    id: '17',
    title: 'Biology Fundamentals',
    description: 'Understanding life at its core.',
    price: 27,
    author: 'John Doe',
    category: 'Science',
    thumbnail: 'https://images.unsplash.com/photo-1578496480157-697fc14d2e55',
    authorId: "2",
  },
  {
    id: '18',
    title: 'Medieval Times',
    description: 'Life in the Middle Ages explored.',
    price: 23,
    author: 'Dr. Michael Chen',
    category: 'History',
    thumbnail: 'https://images.unsplash.com/photo-1513138990900-4f77e62d2e57',
    authorId: "7",
  },
  {
    id: '19',
    title: 'The Dark Forest',
    description: 'A thrilling fantasy adventure in mysterious woods.',
    price: 21,
    author: 'Aria Smith',
    category: 'Fantasy',
    thumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3',
    authorId: "4",
  },
  {
    id: '20',
    title: 'Nelson Mandela Story',
    description: 'The remarkable journey of a freedom fighter.',
    price: 31,
    author: 'Sarah Johnson',
    category: 'Biography',
    thumbnail: 'https://images.unsplash.com/photo-1512820790803-83ca734da794',
    authorId: "6",
  },
];